### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by Axkaban** [speed2fast/prj-rev-bwfs-tea-cozy#1]
Thank you for the comments!
[https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L8](https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L8)

Great use of href on same page location:
[https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L13](https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L13)

Awesome work with descriptive and correlated classes and ids!
[https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L22-L23](https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L22-L23)

Quick question... why did you leave everything out of the body? [https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L93-L94](https://github.com/speed2fast/prj-rev-bwfs-tea-cozy/blob/master/Project_teaCozy-final/index.html#L93-L94)

**Comment by speed2fast** [comment]
Thank you for the feedback.  BTW, I left everything out of the body by mistake.  Just carelessness on my part.
