### ISSUE TITLE
Overall

### ISSUE THREAD

**Issue by Axkaban** [speed2fast/prj-rev-bwfs-tea-cozy#3]
Awesome! 
200 OK Pass!

Now, I may suggest to take those px measurements and add to the flexbox responsiveness by applying more responsive measure systems like percentages, `em`s, `rem`s or `vh` and `vw`. 

Great work! Stay in the body! lol
Here's some info on viewport measurements  (`vh`, `vw`):
[https://css-tricks.com/viewport-sized-typography/](https://css-tricks.com/viewport-sized-typography/)
also on `em`s and `rem`s:
[https://css-tricks.com/rem-global-em-local/](https://css-tricks.com/rem-global-em-local/)

Best of luck!

**Comment by speed2fast** [comment]
lol,  yes, I will be more careful about staying in the body.  Thank you for the article on viewport measurements,  It looks quite seamless from the example, I will give it a try.
